### ISSUE TITLE
BigQuery support?

### ISSUE THREAD

**Issue by maikelnight1234** [mathworks-ref-arch/mathworks-gcp-support#1]
Hi,

I managed to connect to GCP Storage, but was wondering if there is a similar way to connect MATLAB with BigQuery...?

Thanks!
Mike.

**Comment by pallavikar** [comment]
Hi @maikelnight1234 ,

Thanks for reaching out. Great to hear you were able to connect to the Cloud Storage  API. 
We have also developed a connector for Google BigQuery and will be releasing it very soon (1-2 weeks max).

Can you give me a timeline for your requirements? 
If it is very urgent (within days) I can provide you with a pre-release. In that case we should connect over a short call so that I can introduce to the package and then send it to you over sftp.

**Comment by pallavikar** [comment]
Hi @maikelnight1234 ,

Support for Google BigQuery has been added [here](https://github.com/mathworks-ref-arch/matlab-google-bigquery).
Please note that you also need the [matlab-gcp-common](https://github.com/mathworks-ref-arch/matlab-gcp-common) library.

The easiest way to fetch this repo and all required dependencies, is to clone the top-level repository using:
```
git clone --recursive https://github.com/mathworks-ref-arch/mathworks-gcp-support.git
```
